In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer/customer.csv


In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("/kaggle/input/customer/customer.csv")

In [4]:
df.sample(5)

age  gender review education purchased
9    74    Male   Good        UG       Yes
28   48    Male   Poor    School        No
43   27    Male   Poor        PG        No
25   57  Female   Good    School        No
19   97    Male   Poor        PG       Yes

In [5]:
df=df.iloc[:,2:]

In [6]:
df.sample(5)

review education purchased
30  Average        UG        No
20  Average    School       Yes
25     Good    School        No
43     Poor        PG        No
0   Average    School        No

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],
                                                      test_size=0.2)

In [8]:
X_train.shape,X_test.shape

((40, 2), (10, 2))

# OrdinalEncoding

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [11]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [13]:
X_train

array([[2., 2.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

#  LabelEncoding

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
 le=LabelEncoder()

In [17]:
le.fit(y_train)

LabelEncoder()

In [18]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [19]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [20]:
y_train

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In [21]:
y_test

array([1, 1, 1, 0, 1, 0, 0, 0, 1, 0])